-- Orden de borrado por dependencias
DROP TABLE IF EXISTS ORDENES CASCADE;
DROP TABLE IF EXISTS CLIENTES CASCADE;
DROP TABLE IF EXISTS PRODUCTOS CASCADE;
DROP TABLE IF EXISTS SITUACIONES CASCADE;

-- =======================
--  CLIENTES
-- =======================
CREATE TABLE IF NOT EXISTS CLIENTES (
  CLI_ID BIGSERIAL PRIMARY KEY,
  CLI_RAZON_SOCIAL VARCHAR(255),
  CLI_CUIT VARCHAR(20) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_clientes_cuit ON CLIENTES(CLI_CUIT);

-- =======================
--  PRODUCTOS
-- =======================
CREATE TABLE IF NOT EXISTS PRODUCTOS (
  PRD_ID BIGSERIAL PRIMARY KEY,
  PRD_CODIGO_PRODUCTO VARCHAR(64) NOT NULL,
  PRD_DESCRIPCION VARCHAR(255)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_productos_codigo ON PRODUCTOS(PRD_CODIGO_PRODUCTO);

-- =======================
--  SITUACIONES
-- =======================
CREATE TABLE IF NOT EXISTS SITUACIONES (
  SIT_ID BIGSERIAL PRIMARY KEY,
  SIT_ESTADO_CLAVE VARCHAR(64) NOT NULL,
  SIR_DESCRIPCION VARCHAR(255)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_situaciones_clave ON SITUACIONES(SIT_ESTADO_CLAVE);

-- =======================
--  ORDENES
-- =======================
CREATE TABLE IF NOT EXISTS ORDENES (
  ORD_ID BIGSERIAL PRIMARY KEY,
  ORD_ANIO INTEGER NOT NULL,
  ORD_NRO_PLAN VARCHAR(255) NOT NULL,
  ORD_ORDEN_INTERNA VARCHAR(255),
  ORD_CLI_ID BIGINT,
  ORD_PRD_ID BIGINT,
  ORD_SIT_ID BIGINT,
  ORD_FECHA_INICIO TIMESTAMP,
  ORD_CANTIDAD INTEGER,
  ORD_HOJA VARCHAR(64),
  ORD_ETIQUETA VARCHAR(64),
  ORD_FECHA_FINALIZACION TIMESTAMP,
  ORD_LOTE_PRODUCCION INTEGER,
  ORD_SERIES INTEGER,
  ORD_OBSERVACION VARCHAR(1024)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_ordenes_plan ON ORDENES(ORD_NRO_PLAN);

ALTER TABLE ORDENES
  ADD CONSTRAINT fk_ordenes_cliente
    FOREIGN KEY (ORD_CLI_ID) REFERENCES CLIENTES(CLI_ID) ON UPDATE CASCADE ON DELETE SET NULL,
  ADD CONSTRAINT fk_ordenes_producto
    FOREIGN KEY (ORD_PRD_ID) REFERENCES PRODUCTOS(PRD_ID) ON UPDATE CASCADE ON DELETE SET NULL,
  ADD CONSTRAINT fk_ordenes_situacion
    FOREIGN KEY (ORD_SIT_ID) REFERENCES SITUACIONES(SIT_ID) ON UPDATE CASCADE ON DELETE SET NULL;


-- =======================
--  DATOS ESTATICOS
-- =======================
INSERT INTO SITUACIONES(SIT_ESTADO_CLAVE,SIR_DESCRIPCION) VALUES
  ('REVISAR PLANO','EL PLANO PRESENTA DEFICIENCIAS A CORREGIR'),
  ('PLANIFICADO','POSEE HOJA DE PRODUCCION, PERO AUN NO ESTA EN PRODUCCION'),
  ('EN PROCESO','ENTRO A PRODUCCION'),
  ('TERMINADO','PRODUCTO TERMINADO'),
  ('FALTA MATERIAL','EXISTE UNA LIMITANTE DE MATERIAL PARA SU CULMINACION - STAND BY')
ON CONFLICT DO NOTHING;

-- =======================
--  DATOS PRUEBAS
-- =======================
INSERT INTO CLIENTES(CLI_RAZON_SOCIAL,CLI_CUIT) VALUES ('Cliente Demo 1','1-12345678-9') ON CONFLICT DO NOTHING;
INSERT INTO PRODUCTOS(PRD_CODIGO_PRODUCTO,PRD_DESCRIPCION) VALUES 
    ('C1244','CHICOTE ADAPTADOR MOTORES HIDRAULICOS - COCM00144'),
    ('C1004','INST. ELÉCTRICA TOLVA AUTODESCARGABLE COMOFRA INNOVA'),
    ('C1008','INST. ELÉCTRICA FERTILIZANTE INNOVA 12500 - 17500 LTS'),
    ('C1048','CAJA RADIADOR - CABLE CORTO'),
    ('C1045','CAJA RADIADOR - CABLE LARGO'),
    ('C1176','PROLONGACIÓN 3 VÍAS WP- 3 METROS'),
    ('C1234','RAMAL ELECT. GRINGA DOSIS VARIABLE MODULAR - ECU 1 - COCM00140'),
    ('C1236','RAMAL ELECT. GRINGA DOSIS VARIABLE MODULAR - ECU 2-  COCM00141'),
    ('C1043','CABLE RIENDA UNIVERSAL 10 METROS - COCM00071') 
ON CONFLICT DO NOTHING;