-- =======================
--  TAREAS
-- =======================
CREATE TABLE IF NOT EXISTS TAREAS (
  TAR_ID BIGSERIAL PRIMARY KEY,
  TAR_ORD_ID BIGINT NOT NULL REFERENCES ORDENES(ORD_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  TAR_OPE_ID BIGINT NOT NULL REFERENCES OPERACIONES(OPE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  TAR_NRO_MAQUINA INT NOT NULL,
  TAR_USR_ID  BIGINT NOT NULL REFERENCES USUARIOS(USR_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  TAR_FECHA_INICIO TIMESTAMP NOT NULL,
  TAR_FECHA_FIN TIMESTAMP,
  TAR_CANTIDAD INT,
  TAR_OBSERVACIONES VARCHAR(1000),
  aud_usr_ins varchar(250) NOT NULL,
  aud_usr_upd varchar(250) NOT NULL,
  aud_fecha_ins timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  aud_fecha_upd timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

