version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: carmar-postgres
    environment:
      POSTGRES_DB: carmardb
      POSTGRES_USER: carmaradminuser
      POSTGRES_PASSWORD: c4rm4rP4$
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1",
        ]
      interval: 10s
      timeout: 5s
      retries: 6
volumes:
  pgdata:
